### ISSUE TITLE
[Any] is not a subtype of ()

### ISSUE THREAD

**Issue by remithomas** [StephenHaney/Swift-Custom-Events#4]
Using Xcode 6.0.1, I got this error: **[Any] is not a subtype of ()** with the simple code of
```swift
cat.events.listenTo("meow", {
  println("Human: Awww, what a cute kitty *pets cat*");
});
```
or
```swift 
cat.events.listenTo("meow", self.dayDream);
```

**Comment by StephenHaney** [comment]
Very sorry about this - I didn't do much testing after a contributor added some new code. I believe I've fixed the issue and also updated the syntax for Swift 6.2 on Xcode 6.3 beta 2 (so if you're using 6.0.1 you may have to make a few small syntax changes). Let me know how it works for you!

**Comment by remithomas** [comment]
It works perfect !
Thanks a lot !
